MVC_CI-Platform/CI-platform/CI-platform/Areas/User/Controllers/StoryController.cs
using Microsoft.AspNetCore.Mvc;
using CI.Repository.Repository.IRepository;
using System.Security.Claims;
using CI.Models;
using CI_platform.Areas.User.Controllers;

namespace CI_platform.Controllers
{
    [Area("User")]
    public class StoryController : Controller
    {
        private readonly IAllRepository allRepository;
        public StoryController(IAllRepository _allRepository)
        {
            allRepository = _allRepository;
        }




        [Route("stories")]
        public IActionResult StoryListing(string searchString, int? pageNumber)
        {
            long user_id = long.Parse(User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Sid).Value);


          
            const int pageSize = 3;

            // Get all stories
            CI.Models.ViewModels.Mission stories = allRepository.Story.GetStories(user_id);

         

            // Search for story if search parameter is provided
            if (!string.IsNullOrEmpty(searchString))
            {
                stories.Stories = stories.Stories.Where(b => b.Title.ToLower().Contains(searchString)).ToList();
            }

            // Paginate the Mission using the requested page number and page size
            stories.TotalPages = (int)Math.Ceiling(stories.Stories.Count / (double)pageSize);
            stories.PageNumber = pageNumber ?? 1;
            stories.Stories = stories.Stories.Skip((stories.PageNumber - 1) * pageSize).Take(pageSize).ToList();

            stories.SearchString = searchString;

            return View(stories);
        }



        [HttpPost]
        [Route("stories")]
        public JsonResult StoryListing(int page_index, string key)
        {
            long user_id = long.Parse(User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Sid).Value);


            CI.Models.ViewModels.Mission stories = allRepository.Story.GetFileredStories(page_index, user_id);
            var next_stories = this.RenderViewAsync("story_partial", stories, true);
            return Json(new { next_stories });


        }


        [Route("stories/share")]
        public IActionResult ShareStory()
        {
            long user_id = long.Parse(User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Sid).Value);
            List<Mission> missions = allRepository.Story.Get_User_Missions(user_id);
            return View(missions);
            ViewBag.success = "share story successfull";
        }
        [HttpPost]
        [Route("stories/share")]
        public JsonResult ShareStory(long story_id, long mission_id, string title, string published_date, string mystory, List<string> media, string type)
        {
            long user_id = long.Parse(User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Sid).Value);
            if (type == "PENDING")
            {
                bool success = allRepository.Story.AddStory(user_id, story_id, mission_id, title, published_date, mystory, media, type);
                return Json(new { success });
                ViewBag.success = "share story  view successfull";

            }
            else
            {
                bool success = allRepository.Story.AddStory(user_id, 0, mission_id, title, published_date, mystory, media, type);
                return Json(new { success });
                ViewBag.success = "share story draft view successfull";

            }

            ViewData["ShareStory"] = "True";
        }

        [Route("stories/detail/{id}")]
        public IActionResult StoryDetail(long id)
        {
            if (User.Identity.IsAuthenticated)
            {
                long user_id = long.Parse(User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Sid).Value);
            

                CI.Models.ViewModels.StoryViewModel story = allRepository.Story.GetStory(user_id, id);
                if (story is not null)
                {
                    allRepository.Story.Add_View(user_id, id);
                    return View(story);
                }
                else
                {
                    return View("page_not_found");
                }

            }
            else
            {
                return RedirectToAction("login", "userAuthentication", new { ReturnUrl = $"stories/detail/{id}" });
            }
        }

        [HttpPost]
        [Route("stories/detail/{id}")]
        public JsonResult StoryDetail(long user_id, long story_id, List<long> co_workers)
        {

            bool success = allRepository.Story.Recommend(user_id, story_id, co_workers);
            return Json(new { success });

        }
    }
}

MVC_CI-Platform/CI-platform/CI-platform/Views/Shared/City_partial.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model CI.Models.ViewModels.Mission
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor Accesor
@{
    if (Model.Cities is null)
    {
        foreach (var item in Model.Country)
        {
            foreach (var city in item.Cities)
            {


                if (Context.Session.GetString("city") is not null)
                {


                    if (city.CityId == long.Parse(Context.Session.GetString("city")))
                    {
                        <span class="dropdown-item">
                            <input class="form-check-input" checked type="checkbox" onchange="addcities('@city.Name')" value="" id="@city.Name">
                            <label class="form-check-label" for="flexCheckDefault">
                                @city.Name
                            </label>
                        </span>
                    }
                    else
                    {
                        <span class="dropdown-item">
                            <input class="form-check-input" type="checkbox" onchange="addcities('@city.Name')" value="" id="@city.Name">
                            <label class="form-check-label" for="flexCheckDefault">
                                @city.Name
                            </label>
                        </span>
                    }
                }
                else
                {
                    <span class="dropdown-item">
                        <input class="form-check-input" type="checkbox" onchange="addcities('@city.Name')" value="" id="@city.Name">
                        <label class="form-check-label" for="flexCheckDefault">
                            @city.Name
                        </label>
                    </span>
                }
            }
        }
    }
    else
    {
        foreach (var city in Model.Cities)
        {
            <span class="dropdown-item">
                <input class="form-check-input" type="checkbox" onchange="addcities('@city.Name')" value="" id="@city.Name">
                <label class="form-check-label" for="flexCheckDefault">
                    @city.Name
                </label>
            </span>
        }
    }
}

MVC_CI-Platform/CI-platform/CI-platform/Views/Shared/EditMission.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model CI.Models.ViewModels.AdminMission

@{


    <div class="particalEditmission m-5" style="margin:50px;">

        <form asp-area="Admin" asp-action="AddMission" id="form" asp-controller="Mission" method="post" enctype="multipart/form-data">
            <input asp-for=MissionId id="id" name="id" type="hidden" class="form-group form-control mb-4 " aria-label="Default" aria-describedby="inputGroup-sizing-default">

            <div style="margin:40px;">
                @*mission title*@
                <div class="mt-2 w-100">
                    <lable>Title</lable>
                    <input asp-for=Title type="text" class="form-group form-control mb-4 " aria-label="Default" aria-describedby="inputGroup-sizing-default">
                    <span asp-validation-for=Title class="d-block text-danger"></span>

                </div>

                @*mission Description*@
                <lable>Description</lable>
                <textarea asp-for=Description type="text" rows="4" class="form-control  mb-4" aria-label="Default" aria-describedby="inputGroup-sizing-default">
                                                </textarea>
                <span asp-validation-for=Description class="d-block text-danger"></span>

                @*mission Organazion*@
                <lable>Organazion Name</lable>
                <input asp-for=OrganizationName type="text" class="form-control mb-4" aria-label="Default" aria-describedby="inputGroup-sizing-default">
                <span asp-validation-for=OrganizationName class="d-block text-danger"></span>


                @*mission Organazion Details*@
                <lable>Organazion Details</lable>
                <textarea asp-for=OrganizationDetail type="text" rows="4" class="form-control mb-4" aria-label="Default" aria-describedby="inputGroup-sizing-default">
                                                                                                                    </textarea>
                <span asp-validation-for=OrganizationDetail class="d-block text-danger"></span>


                @*start and end date & deadline*@
                <div class="row mb-5">
                    <div class="col-sm-12 col-lg-4 col-md-6">
                        <lable>Starting date</lable>
                        <input asp-for=StartDate class=" form-control">
                        <span asp-validation-for=StartDate class="d-block text-danger"></span>

                    </div>

                    <div class="col-sm-12 col-lg-4 col-md-6">
                        <lable>End date</lable>
                        <input asp-for=EndDate class=" form-control">
                        <span asp-validation-for=EndDate class="d-block text-danger"></span>

                    </div>


                    <div class="col-sm-12 col-lg-4 col-md-12">
                        <lable>Registration DeadLine</lable>
                        <input asp-for=Deadline class=" form-control">
                        <span asp-validation-for=Deadline class="d-block text-danger"></span>

                    </div>
                </div>

                @*available seats*@
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="inputGroup-sizing-default">Total seats</span>
                    </div>
                    <input asp-for=TotalSeats type="text" class="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default">
                </div><span asp-validation-for=TotalSeats class="d-block text-danger"></span>

                @*mission Skill*@
                <div class="row">
                    @*
                        <div class="col-lg-5 mt-2 col-md-5 col-sm-12 ">
                        <label class="form-label">Skill</label>
                        <select asp-for=SkillId class="form-select me-3" aria-label="Select Skill">
                        <option value=0 disabled selected>Select Skill for Mission</option>
                        @{
                        foreach (var Model in Model.skills)
                        {

                        <option value=@Model.SkillId id=@Model.SkillId>@Model.SkillName</option>
                        }
                        }
                        </select>
                        </div>
                    *@

                    <div class="col-lg-5 mt-2 col-md-5 col-sm-12">
                        <label class="form-label">Skills</label>
                        <select asp-for="SelectedSkills" id="@Model.SelectedSkills" class="form-select me-3" aria-label="Select Skills" multiple>
                            <option value="0" disabled selected>Select Skills for Mission</option>
                            @foreach (var skill in Model.skills.Where(x => x.Status == 1))
                            {
                                <option value="@skill.SkillId">@skill.SkillName</option>
                            }
                        </select>


                    </div>


                    @*mission Theme*@
                    <div class="col-lg-5 mt-2 col-md-5 col-sm-12">
                        <label class="form-label">Theme</label>
                        <select asp-for=MissionThemeId class="form-select me-3" aria-label="Select Theme">
                            <option value=0 disabled selected>Select Theme for Mission</option>
                            @{
                                foreach (var Model in Model.themes.Where(x => x.Status == 1))
                                {

                                    <option value=@Model.MissionThemeId id=@Model.MissionThemeId>@Model.Title</option>
                                }
                            }
                        </select>
                        <span asp-validation-for=MissionThemeId class="d-block text-danger"></span>

                    </div>
                </div>
                @*Country*@

                <div class="row">
                    <div class="col-lg-5 mt-2 col-md-5 col-sm-12">
                        <label class="form-label">Country</label>
                        <select onchange="displaycities('Country')" asp-for=CountryId class="form-select me-3 Country" aria-label="Select Country">
                            <option  value=0 disabled selected>Select Country for Mission</option>
                            @{
                                foreach (var Model in Model.Country)
                                {

                                    <option  value=@Model.CountryId id=@Model.CountryId>@Model.Name</option>
                                }
                            }
                        </select>
                        <span asp-validation-for=CountryId class="d-block text-danger"></span>

                    </div>


                    @*Cities*@
                    <div class="col-lg-5 mt-2 col-md-5 col-sm-12">
                        <label class="form-label">City</label>
                        <select asp-for=CityId class="form-select me-3" aria-label="Select City">
                            <option value=0 disabled selected>Select Country for Mission</option>
                            @{
                                foreach (var Model in Model.Cities)
                                {

                                    <option value=@Model.CityId id=@Model.CityId class="country-@Model.CountryId modelcities">@Model.Name</option>
                                }
                            }
                        </select>
                        <span asp-validation-for=CityId class="d-block text-danger"></span>

                    </div>
                </div>
                @*availabilities*@
                <div class="col-lg-6 mt-2 col-md-6 mb-4 ">
                    <label class="form-label">Availablity</label><select asp-for=Availability id='avilablity' class="form-select me-3" aria-label="Select Mission">
                        <option value=0 disabled selected>Select Your Availablity</option>
                        <option value='Weekly'>Weekly</option>
                        <option value='Daily'>Daily</option>

                    </select>
                    <span asp-validation-for=Availability class="d-block text-danger"></span>

                </div>
                @*mission type*@
                @*
                    <div class="col-lg-6 mt-2 col-md-6 mb-4 ">
                    <label class="form-label">Mission Type</label><select asp-for=MissionType id='avilablity' class="form-select me-3" aria-label="Select Mission">
                    <option value=0 disabled selected>Select Your MissionType</option>
                    <option value='GOAL'>GOAL</option>
                    <option value='TIME'>TIME</option>

                    </select>
                    </div>
                *@
                <div class="form-group col-12 col-md-6 mb-3">
                    <label asp-for="MissionType" class="form-label text-muted">Mission Type</label>
                    <select asp-for="MissionType" class="form-control">
                        <option value="">Select Mission Type</option>
                        <option value="TIME">Time</option>
                        <option value="GOAL">Goal</option>
                    </select>
                    <span asp-validation-for="MissionType" class="text-ci-danger fs-7"></span>
                </div>
                <div class="form-group col-12 col-md-6 mb-3 goal-item d-none">
                    <label asp-for="GoalValue" class="form-label text-muted">Goal Action</label>
                    <input asp-for="GoalValue" class="form-control" placeholder="Enter Goal Action" />
                    <span asp-validation-for="GoalValue" class="text-ci-danger fs-7"></span>
                </div>
                <div class="form-group col-12 col-md-6 mb-3 goal-item d-none">
                    <label asp-for="GoalObjectiveText" class="form-label text-muted">Goal Objective Text</label>
                    <input asp-for="GoalObjectiveText" class="form-control" placeholder="Enter Goal Objective Text" />
                    <span asp-validation-for="GoalObjectiveText" class="text-ci-danger fs-7"></span>
                </div>
                @*
                    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


                    @*experience*@
                <h4>Images</h4>
                @if (Model.Missionmedia == null || !Model.Missionmedia.Any())
                {
                    <div class="form-group">
                        <label>Images</label>
                        <input type="file" name="files" multiple required />
                    </div>
                }
                else
                {
                    <div class="form-group">
                        <label>Images</label>
                        <input type="file" name="files" multiple />
                    </div>
                }
                <div class="d-flex">
                    @{
                        foreach (var Model in Model.Missionmedia)
                        {
                            <div id="image-@Model.MissionMediaId">
                                <img style="width:100px; height:100px" src="@Model.MediaPath" />
                                <img class="height m-2" style="height: 20px;" onclick="Declinemedia(@Model.MissionMediaId)" src="~/images/cancled-red.png" />
                            </div>
                        }
                    }
                </div>
                <hr />
                <h4>Documents</h4>
                <div class="form-group mb-3">
                    <label for="fileInput">Document Upload:</label>
                    <input type="file" class="form-control-file" id="fileInput" name="fileInput">
                </div>
                <div class="d-flex document flex-wrap">
                    @{
                        if (Model?.missionDocuments?.Count != 0)
                        {
                            foreach (var item in Model?.missionDocuments)
                            {
                                <div class="d-flex ms-2 mt-2 align-items-center border rounded-pill p-1" id="document-@item.MissionDocumentId">
                                    <a href='~/documents/@item.DocumentPath' target='_blank' style='text-decoration:none; color:black;'>
                                        <img class=" ms-2" src="~/images/doc.png" alt="" />
                                        <span class="ms-1 me-2">@item.DocumentName</span>
                                    </a>
                                    <img class="height m-2" style="height: 20px;" onclick="Declinedocument(@item.MissionDocumentId)" src="~/images/cancled-red.png" />
                                </div>
                            }
                        }
                        else
                        {
                            <h6>No Document Uploaded</h6>
                        }
                    }
                </div>
                <div class="modal-footer">
                    <button class="btn btn-outline-danger rounded-pill" type="submit">Save</button>
                    <button type="reset" class="btn rounded-pill btn-outline-secondary" onclick="changelayout()">Cancle</button>
                </div>
            </div>
        </form>
    </div>
}

<script>
      $("#MissionType").change((e)=>{
        if(e.target.value === "GOAL")
        $(".goal-item").removeClass("d-none");
        else
        $(".goal-item").addClass("d-none");
    });

</script>

@section scripts{
    @{
    <partial name="_ValidationScriptsPartial" />
    }
    }

MVC_CI-Platform/CI-platform/CI-platform/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using System.Security.Claims
@inject IHttpContextAccessor Accesor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CI_platform</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/@ViewData["css"]" asp-append-version="true" />
    <link rel="stylesheet" href="~/CI_platform.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-datepicker.css" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script>
            toastr.options = {
            "closeButton": true,
            "debug": false,"newestOnTop": false,"progressBar": true,"positionClass": "toast-top-right","preventDuplicates": false,"onclick": null,"showDuration": "300","hideDuration": "1000","timeOut": "2000",
            "extendedTimeOut": "1000","showEasing": "swing","hideEasing": "swing","showMethod": "slideDown","hideMethod": "slideUp"
        }

    </script>

</head>
<body onload="setpages();">
    @{
        if (@ViewData["home"] == "true")
        {
            <script>
                toastr.success("Authentication Successfull")
            </script>
        }
        if (@ViewData["Volunteering_Timesheet"] == "edit")
        {
            <script>
                toastr.success("edit Successfull")
            </script>
        }
        if (@ViewData["Volunteering_Timesheet"] == "time")
        {
            <script>
                toastr.success("Volunteer Hour Add Successfull")
            </script>
        }
        if (@ViewData["Volunteering_Timesheet"] == "goal")
        {
            <script>
                toastr.success("Volunteer Goal Add Successfull")
            </script>
        }
        if (@ViewData["Volunteering_Timesheet"] == "timevalid")
        {
            <script>
                toastr.error(" Please Enter Valid Time")
            </script>
        }
        if (@ViewData["Profile"] == "profileError")
        {
            <script>
                toastr.error(" Employee Id is Already used")
            </script>
        }

    }

    <div class="offcanvas offcanvas-start" data-bs-scroll="true" tabindex="-1" id="sidebar" aria-labelledby="offcanvasWithBothOptionsLabel">
        <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="offcanvasWithBothOptionsLabel"></h5>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
           
            <a class="nav-link text-muted" asp-area="" asp-controller="Story" asp-action="storylisting">Stories</a>
            <a class="nav-link text-muted mt-3" asp-area="" asp-controller="Home" asp-action="Privacy">Policy</a>
        </div>
    </div>
    <header>


        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom">
            @* <img src="~/images/logo.png" class="logo" alt="not found" />*@
            <div class="container w-100 d-flex justify-content-between header">
                <img src="~/images/sidebar.png" class="sidebar-button" data-bs-toggle="offcanvas" data-bs-target="#sidebar" aria-controls="offcanvasWithBothOptions" alt="not load" />
                <div class="d-flex pages ">

                    @{
                        if (@Accesor?.HttpContext?.Session.GetString("role") is not null)
                        {
                            <a class="nav-link text-muted" href="/Admin/User/Index">
                                Admin
                            </a>
                        }
                    }


                    <a class="nav-link text-muted" href="/Home">Home</a>
                    @*<span class="nav-link text-muted explore" asp-area="">Explore <img src="~/images/drop-down.png" alt="not load" /></span>*@
                    <a class="nav-link text-muted" href="/stories">Stories</a>
                    @*<a class="nav-link text-muted" asp-area="" asp-controller="Home" asp-action="Index">News</a>*@
                    <a class="nav-link text-muted" href="/Privacy">Policy </a>

                    <select class=" nav-link text-muted form-select me-3" onchange="explore_by(@User?.Claims.FirstOrDefault(c=>c.Type==ClaimTypes.Sid)?.Value)" aria-label="explore By" id="explore">
                        <option disabled selected>Explore</option>
                        <option value="Theme">Theme</option>
                        <option value="Ranked">Ranked</option>
                        <option value="Top Favourite">Top Favourite</option>
                        <option value="Random">Random</option>
                    </select>





                </div>
                <div class="d-flex">

                    <div class="dropdown d-flex align-items-center" style="right: 36px;">
                        <img src="@Accesor.HttpContext.Session.GetString("Avatar")" class="user dropdown-toggle" data-bs-toggle="dropdown" id="navbarDropdown" role="button" aria-haspopup="true" aria-expanded="false" alt="Not load" />
                        <span class="nav-link username text-muted dropdown-toggle" data-bs-toggle="dropdown" id="navbarDropdown" role="button" aria-haspopup="true" aria-expanded="false">@base.User.Identity.Name</span>
                        <img src="~/images/drop-down.png" class="down dropdown-toggle" data-bs-toggle="dropdown" id="navbarDropdown" role="button" aria-haspopup="true" aria-expanded="false" alt="Not load" />
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="width: 191px;">
                            <a class="dropdown-item" href="/profile">Profile</a>
                            <a class="dropdown-item" href="/volunteering_timesheet">Volunteering Timesheet</a>
                            <a class="dropdown-item" href="/logout">LogOut</a>
                        </div>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <main role="main" class="pb-3">
        @RenderBody()
    </main>


    <footer class=" footer bg-dark text-center text-white">
        <!-- Grid container -->
        <div class="container p-4 pb-0">
        </div>
        <!-- Grid container -->
        <!-- Copyright -->
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
            &copy; 2023 - CI_platform -
            <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy policy</a>
        </div>
        <!-- Copyright -->
    </footer>



    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="/lib/bootstrap/dist/js/bootstrap-datepicker.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>